import './globals.css';
import type { Metadata } from 'next';
import { Source_Sans_3 } from 'next/font/google';
import Providers from '@/lib/tanstack-query';

const sourceSans3 = Source_Sans_3({
	variable: '--font-source-sans-3',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${sourceSans3.variable} ${sourceSans3.style} antialiased`}
			>
				<Providers>{children}</Providers>
			</body>
		</html>
	);
}
